### ISSUE TITLE
[rendering] clamp min/max zoom

### ISSUE THREAD

**Issue by ohmec** [ohmec/ohmec#105]
Leaflet allows the zoom values 0..18, but a) zero is broken (background map vanishes); b) anything less than 2.0 shows multiple copies of the globe (though due to a quirk with Leaflet, only renders the overlay content on one of the copies); c) anything greater than say a zoom of 14 or 15 is beyond the accuracy we're looking to attain in the project (see #100). Leaflet allows you to set the minimum and maximum zoom. I'm proposing 2.0 and 15.0.

Zoom at 0.5, showing redundant (and un-layered) copies of underlying map:

![Screen Shot 2021-10-21 at 4 08 04 PM](https://user-images.githubusercontent.com/84106593/138368854-dc9f5556-1ea4-4932-bfb3-8e2d3431147f.png)

Zoom at 14.0:

![Screen Shot 2021-10-21 at 4 07 21 PM](https://user-images.githubusercontent.com/84106593/138368801-0c5b6e6f-235b-44dd-952a-eade9e5e343f.png)

**Comment by warrenjp** [comment]
I really dislike the "multiple earths" and agree that Zoom should be constrained. If the "multiple earths" threshold is around Zoom = 2, then that sounds like a good value for the low end of the scale. Zoom = 15 appears to be appropriate for the top end given our objectives at this time.
