### ISSUE TITLE
Remove or enable toggling of ever-present background state borders and state/city names?

### ISSUE THREAD

**Issue by warrenjp** [ohmec/ohmec#125]
In conversation with David Chang, it became clear that it is disrespectful to "suggest" the present day borders and names when viewing the land and indigenous nations from a historical perspective. Moreover, since one can always slide the time bar to the present to see present-day borders, it's reasonable to remove these borders and labels from the background so that the historic borders, tribes, and claims are not diminished by the presence of the present-day borders and labels.

If it is found to be desirable to show the present-day borders and labels when looking at historic times, then a compromise can be struck by enabling the toggle of these present-day borders and labels with a UI switch that is defaulted to off.

**Comment by warrenjp** [comment]
@ohmec We will need to discuss the above issue and decide which path to take, if any.

**Comment by ohmec** [comment]
We can do several things here, from going to a pure satellite-based map, to having users select a map, to making the background text more faint. At the moment we're using `mapbox/light-v9`, which is the lightest one, but there are other services we can research. The answer is in the [TileLayer](https://leafletjs.com/reference-1.7.1.html#tilelayer).

**Comment by ohmec** [comment]
Check this out (replace the appropriate lines of `ohmec.js`) for example:

```javascript
L.tileLayer('https://stamen-tiles-{s}.a.ssl.fastly.net/watercolor/{z}/{x}/{y}.jpg', {
  maxZoom: 18,
  attribution: 'Map tiles by <a href="http://stamen.com">Stamen Design</a>, ' +
               '<a href="http://creativecommons.org/licenses/by/3.0">CC BY 3.0</a> ' +
               '&mdash; Map data &copy; ' +
               '<a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors',
  tileSize: 512,
  zoomOffset: -1
}).addTo(ohmap);
```

**Comment by ohmec** [comment]
Or this one:

```javascript
L.tileLayer('https://stamen-tiles-{s}.a.ssl.fastly.net/terrain-background/{z}/{x}/{y}{r}.jpg', {
  maxZoom: 18,
  attribution: 'Map tiles by <a href="http://stamen.com">Stamen Design</a>, ' +
               '<a href="http://creativecommons.org/licenses/by/3.0">CC BY 3.0</a> ' +
               '&mdash; Map data &copy; ' +
               '<a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors',
  tileSize: 512,
  zoomOffset: -1
}).addTo(ohmap);
```

I do think there is some benefit to compare against modern borders, but I do agree removing the labels would be a good upgrade.

**Comment by ohmec** [comment]
Better yet, check out the list as examples: http://leaflet-extras.github.io/leaflet-providers/preview/

**Comment by warrenjp** [comment]
This is my favorite:
Esri.WorldPhysical

These are also very good:
Esri.WorldImagery
USGS.USImagery

Others that wold work, but I don't like as much:
Esri.WorldShadedRelief
MtbMap
GeoportailFrance.orthos

**Comment by ohmec** [comment]
> This is my favorite: Esri.WorldPhysical

Dang, I like this one too, but the maxZoom is 9 which is not very high. I'll add it to the list but need to cap the zoom there

**Comment by warrenjp** [comment]
Ah, that's too bad. Which one(s) of the backgrounds allows us to Zoom all the way to our current maxZoom?
