### ISSUE TITLE
Connect to native-lands.ca API and use GeoJSON data therein as baseline indigenous nations data for ohmec

### ISSUE THREAD

**Issue by warrenjp** [ohmec/ohmec#129]
https://native-land.ca/

Given that this site was recommended and it is updated regularly and it has an API, this is likely a far superior starting point for the integration of indigenous peoples into our map.

**Comment by warrenjp** [comment]
Adding in Scott's comments sent via email:

_wow, awesome, this is incredible and inspiring. but the patchwork nature of it frightens me a bit. also: language vs culture vs tribe vs treaty. whew.

first impressions / stream of consciousness: this is the messy reality that we likely have in the future if we want to get it right; a timeline slider should would be nice :); if we were to plug into their API, it could go very smoothly, but I wouldn't feel right without a big sit down with the "supporter's circle" being involved slash getting into the supporter's circle in order to give back; nice caveats right up front that are good to learn from; they're using something other than leaflet but similar, need to research (eventually)._

**Comment by warrenjp** [comment]
as reference, language-based vs. tribe:

https://en.wikipedia.org/wiki/Indigenous_languages_of_the_Americas#/media/File:Langs_N.Amer.svg

**Comment by ohmec** [comment]
[https://biamaps.doi.gov/indianlands](https://biamaps.doi.gov/indianlands/) is another resource, showing current reservation occupation.

**Comment by ohmec** [comment]
I consider this done for Phase I. The NL database has been updated recently (last week in #256), and the integration into the `_na` database is relatively readable. Anything additional would be post Phase I, and hopefully in coordination with that organization.
