### ISSUE TITLE
Update OHMEC summary

### ISSUE THREAD

**Issue by warrenjp** [ohmec/ohmec#135]
Proposed summary:

_OHMEC is a free, open-source geography project, with a goal of representing all historical indigenous lands and political boundaries in a unified database. The uniqueness of OHMEC is its ability to represent these lands and boundaries on any date, as well as being able to show the dynamic changes in lands and boundaries from any point in history to the present._

There are probably a couple of places it should be updated: index.html, README, Ohmec documentation, etc.

**Comment by warrenjp** [comment]
For reference, the current summary reads as follows:

_The Open History Map Exploration project (OHMEC) is a free, open-source developed geography project with a goal of representing all historical political boundaries in a unified database._

**Comment by warrenjp** [comment]
files updated:
- index.html
- The OHMEC project presentation
- README

**Comment by warrenjp** [comment]
@ohmec Looks like you will have to modify the "About" description for the ohmec Github Repository. I can't seem to find any place to edit this text description, which is the old description of the ohmec project.

**Comment by ohmec** [comment]
@warrenjp I have updated the About blurb. I also see your changes to the Slides document. In future, it is helpful to enter Suggesting Mode first so that it is easier for others to see the changes.
