### ISSUE TITLE
[database] clean up sources

### ISSUE THREAD

**Issue by ohmec** [ohmec/ohmec#81]
At the moment the source information is a bit paltry for the database. Before it gets too much further the database should be scrubbed a bit to add the source reference material as is suggested for most historical features.

**Comment by warrenjp** [comment]
@ohmec Do we have the capability of allowing multiple sources to be cited for the same feature? What about an easy way to cite a single source for multiple features. Moreover, it is clear that there are going to be different sources for the same feature that contradict each other. I would be beneficial to be able to cite all sources and show which one is being followed and which one is not, thus communicating that a conscious decision was made as to which source is more credible.

**Comment by ohmec** [comment]
> @ohmec Do we have the capability of allowing multiple sources to be cited for the same feature? What about an easy way to cite a single source for multiple features. Moreover, it is clear that there are going to be different sources for the same feature that contradict each other. I would be beneficial to be able to cite all sources and show which one is being followed and which one is not, thus communicating that a conscious decision was made as to which source is more credible.

Ah, yes we do, and I forgot to tag this when it went in months ago. It was added in PR #156, silently alas. But the documentation was updated at that time.

**Comment by ohmec** [comment]
I'm leaving this open and calling it a P1 for Phase I to make sure every feature has at least one source. I will also add `source` or `sources` as a required property going forward after that goes in. This doesn't mean they'll be "cleaned up", but at least they will all be sourced to at least a minimal level. It would be nice to keep linkrot away and make sure all source links are alive.
